[profile.default]
solc = '0.8.17'
src = 'contracts'
out = 'out'
libs = ['lib', "node_modules"]
test = 'test/foundry'
# remappings = [
#   'openzeppelin-contracts/=lib/openzeppelin-contracts/'
# ]

[profile.test]
src = 'test/foundry'

[rpc_endpoints]
anvil = "${ANVIL_RPC_URL}"
sepolia="${SEPOLIA_RPC_URL}"
mumbai="${MUMBAI_RPC_URL}"
polygon="${POLYGON_RPC_URL}"

[fmt]
line_length = 120
tab_width = 2
# bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
